### PR TITLE
balance tweaks - part 2

### PR DESCRIPTION
**Pull request by BrotherHangyul**
## About The Pull Request
various balance  and bug fixes/tweaks.

- fixes an icon bug w/ the combat carbine. hopefully. i am praying.
- broadly reduces the damage of bullets by increments of five.
- disables dual-wielding on a lot of the more powerful / spammy handguns and revolvers. increases the recoil penalty of dual wielding (no seriously we should've done this shit earlier)
the current guns exempt from being barred from dual wielding are .45 revolvers and 9mm pistols, excluding those with bonus damage and/or burstfire toggles. i may have missed some - apologies if i have.
- removes the ability to make golems w/ sheets.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
fix: icon / map fixes
balance: projectile nerfs / minor dungeon addition. reduces the availability of dual-wielding pistols and revolvers.
/:cl:

### CODE REVIEW

**Comment by xTrainx** [comment]
dual wielding my beloved

**Comment by xTrainx** [comment]
i need you to install the git hooks and then run mapmerger on your pr, preferibly restore your map to the server's current map and then install the hooks, do your changes and run mapmerger so it doens't conflic with other map changes

**Comment by xTrainx** [comment]
the american commonweath rifle has it's sprite bugged, probablly gotta make a new state with -20 at the end

**Comment by Aurrain** [comment]
Going to merge this so I can (hopefully) fix the American Commonwealth Carbine by adding more icon states.

**Comment by Aurrain** [comment]
nvm I found the issue, it's a path issue because of course it is. Gonna force the fix in.

**Pull request merged**
