### PR TITLE
Wardrobe cheapening

### PR DESCRIPTION
**Pull request by githubuser4141**
## About The Pull Request
Makes cosmetic wardrobe clothing cheaper, ableit all the exowear contains small amounts of armor because of armor balance changes. But it's just cosmetic.

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
balance: Cosmetic clothing from wardrobe vendors is now cheaper.
/:cl:

### CODE REVIEW

**Comment by xTrainx** [comment]
instead of making every wardrobe really cheap manually, make the base wardrobe really cheap and leave the other 2 as they are

**Comment by githubuser4141** [comment]
> instead of making every wardrobe really cheap manually, make the base wardrobe really cheap and leave the other 2 as they are

Sure, I didn't do that incase there's some wardrobe variant that vends powerarmor for like 50k caps, but there probably isn't/won't be

**Comment by Aurrain** [comment]
@xTrainx was this ever fixed to where you wanted it to be?

**Comment by xTrainx** [comment]
changes not addressed

**Pull request closed without merging**
