### PR TITLE
Adds Ambulance, BOS Jeep, Normal jeep, and Legion Balloon

### PR DESCRIPTION
**Pull request by DeltaDav**
## About The Pull Request

Well, it says all.
This adds the new vehicules on the Yuma map.

2 ambulance, 
one Normal Jeep,
One BoS jeepn
One Legion balloon.

The legion balloon is in a special spot . The upper canyon has now 2 gates. 
One Ambulance is near the hospital,
The other is near the town clinic.

The normal Jeep is near the superbase.
The BoS jeep is in the BoS base.

### CODE REVIEW

**Comment by DeltaDav** [comment]
image

image

image

image

**Comment by DeltaDav** [comment]
The town scavengers also got new vehicles
image

**Comment by xTrainx** [comment]
wheres the supermutant volkswagens?

**Comment by Yobrocharlie** [comment]
LEGION BALLOON LEGION BALLOON LEGION BALLOON

**Pull request merged**
