### PR TITLE
Craftable cars rudimentary system + Makes all vechicles no longer phazon + Makes them impossible to carry weapons + Trunks.

### PR DESCRIPTION
**Pull request by DeltaDav**
## About The Pull Request

So Cars and Vertibirds have a issue where they are more used for combat than actual transport, and that there is too much on map at round start. 

This PR will lower their numbers, but make them better travel wise. This will also remove their weapons.

### **Trunks**
The Trunks from Big Iron are back.
They can be used to carry more stuff arround the Wasteland.

### **No phazon**
All Vehicule are now their proper and own mecha type :
Normal Vehicule and Combat Vehicule

### **Unarmed**
Now, all vehicules can no longer carry weapons.
Except the Vehicules with Gunners on them.

This is also the case for vertibird. BUT. The vertibirds combat variant are still in code for events. 

### **Carfting**
All regular vehicules can be crafted via the crafting menu. Its a step by step process.
Step 1 : Need to find the proper car wreck and repair that wreck to be a frame.
Step 2 :  Once that frame completed, add the batterie and engine
Step 3 : Add a car seat and Electronics
Step 4 : The fun part : Choose the car and finish.

There are some exception, where the Truck caravan skips Step 2 and Step 3

### **Stat Buffs**
All vehicules, flying or not, have their fuel use reduced, and all ground vehicules have their speed increased

### CODE REVIEW

**Comment by Aurrain** [comment]
Multiple map conflicts, need to be fixed.

**Comment by DeltaDav** [comment]
fixed, ready to merge

**Comment by Defaulterrama** [comment]
NCR Vertibird has more health, more slots, and moves faster and loses less fuel per move than every other Vertibird. Why? Anyway I'd probably fix that before the merge.

**Comment by DeltaDav** [comment]
Mistake on my part, thanks

Le sam. 16 nov. 2024, 06:37, Defaulterrama ***@***.***> a
écrit :

**Comment by Loldaddy5676** [comment]
rather then nuking the ability to provide air support, remove the strafe feature from the vertibirds. this will make it so pilots can't just spin around quickly around ground targets, and the people can just look up and manage to get some seconds to shoot the vertibird while its turning.

**Pull request merged**
