### PR TITLE
Wasteland Flipper: Lamp post repair DLC

### PR DESCRIPTION
**Pull request by AF-Buyrcsp2**
## About The Pull Request
Ports lamp posts to be a child of regular light fixtures, making them fixable and buildable.

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl: Buyrcsp2/Amfai
refactor: Lamp post is now a variant of light fixtures
add: adds a way to build all 5 variant of lamp posts
code: moved around light defines because it keeps getting redefined somehow?
map: replaced the previous version lamp post that now doesn't exist into the new version
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
1000 HP for the frame and it's dense, isn't that durable enough to be used as barricade, for only 5 steel? Cool idea though!

**Comment by AF-Buyrcsp2** [comment]
fair nuff, just need to change some values

**Comment by githubuser4141** [comment]
Aw yeah, I'm not staff or anything, just thought 1000 HP was hugely tanky for just 5 sheets of iron, 750 for a machine feels a bit high, but I do understand our weapons have fairly high DPS (and, megafauna like d-claws have bonus damage on objects and I'm guessing machinery.)

**Comment by xTrainx** [comment]
did you install mapmerger before doing the map changes?

**Comment by AF-Buyrcsp2** [comment]
> did you install mapmerger before doing the map changes?

what the hell is that

**Comment by AF-Buyrcsp2** [comment]
> did you install mapmerger before doing the map changes?

no

**Review by xTrainx — APPROVED** [review]

**Pull request merged**
