### PR TITLE
Tweaks plant+medicine bag item count, adds Bitter barrels, Fixes bottle rack

### PR DESCRIPTION
**Pull request by K4rlox**
## About The Pull Request
Makes the plant bags contain 100 items just like it did before in big iron, not 28, why the fuck was it 28 anyways

medical bag now can contain 20 items

Adds back broc, xander and cactus barrels to legion camp, maps them in
image

Legion bottle racks can now take in the new medicines and bitterdrink in it, thank god

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Legion bitter barrels
mapping: mapped in barrels
tweak: medicine bag now contains 20 items
tweak: plant bag now contains 100 items
fix: bottle rack can now take in bitter, hydra bottles
/:cl:

### CODE REVIEW

**Comment by K4rlox** [comment]
forgot to mention
ports barrels from this PR
https://github.com/Foundation-19/Big-Iron/pull/134

**Comment by xTrainx** [comment]
did you use mapmerger?

**Comment by K4rlox** [comment]
> did you use mapmerger?

no i was told i dont even need to because it auto uses when i build it anyways

**Comment by kooarbiter** [comment]
having plant bags be 28 was really helpful, since if you grew 3 of each plant next to each other and harvested them at the same time, you'd be left with just enough to make seeds for the next planting like 80 percent of the time

**Comment by K4rlox** [comment]
> having plant bags be 28 was really helpful, since if you grew 3 of each plant next to each other and harvested them at the same time, you'd be left with just enough to make seeds for the next planting like 80 percent of the time

its much better to go back to big iron plant bags which carry 100

**Review by xTrainx — APPROVED** [review]

**Review by xTrainx — CHANGES_REQUESTED** [review]
merge conflict

**Comment by K4rlox** [comment]
fuck this

**Pull request closed without merging**
