### PR TITLE
Mechanized bigiron map addon

### PR DESCRIPTION
**Pull request by DeltaDav**
## About The Pull Request
The mechanized Big Iron Update, on the previous code, was actually not complete. With the vehicles, there was supposed to be a extention with the map, but because of the code, it was impossible to add. 

Now with the Hail Mary code, it is now possible. 

This PR adds a new zone south of Yuma. 
Its based on the Californian golf. Meaning, part of the map is in Mexico. 
image
_The yellow area is the part of the map. The Blue area ? In the futur, maybe._ 

image

Things added :
**The USS Eminant Domain**, _Enclave remnant base_ 
Teased since a long time, the USS Eminant Domain, a EX enclave Aircraft Carrier, is now present in the area ! Supposed to serve as assistance to the local Enclave Cell, its now used by beaten down surviving US citizens as their home, after the Enclave disbanding.

image
image

It also adds a New Remnant like role : "US citizens". No Enclave Uniform, or big guns, this remnant role takes inspiration from the Enclave Remnants of Fallout 4's Creation Club. Got a a few loadouts :
_Soldier : Enclave Vest + Combat Helmet + Focused AE9_
_Crewman : Combat Rifle + Utility Vest + Toolbelt + 50 caps + Peacekeeper cap_
_Civilian : 9mm Pistol + 10 caps + Cleaning gear_ 
_Doctor : Wattz1000s + Surgery book + Surgery belt + Lab coat_
_Officer : Wattz1000s + Coat + Officer Cap_

**New Legion Base : The port of Ostia**
A small legion town with its own legion base (in a attempt to give more rp option for the legion). 
Its been moved south of the new area. Normaly a area uncontested by the NCR. Yes, legion subject live here. People that ain't free, buuuuuut can move arround and live with more freedom than most in the legion.  
The Camp part of the town is nearly the same as the current legion camp, just more compact.
The town has : The governors house (with a shop and a slave exhibit on the ground floor, and a some public bath, conference room, and the gouvernors office and room on the first floor.
The town also got a Restaurant, A some Chapel (that can serve as a shitty medical room), few tents and homes, and a Arena / Circus for gladiator fights.

image
image

It also adds 2 new Legion roles : 
Legion Subject (with loadouts for shopkeeps, Restaurant worker, Gladiator, and just civilians)
And Legion Governor **(Warning, this one will be deactivated at first, so it will be only be available in code)**

**Supermutant camp at the location of the old legion camp**
image

Some new dungeons and area :
A car factory (medium difficulty dungeon) 
A mexican town (Easy area) 
A tribe village on the colorado delta (Potential player base) 
Illegal NCR labor camp created by a NCR Brahmin Baron (Easy to Medium dungeon)
A border checkpoint (Medium to hard dungeon) 
Some Raider camps

## Pre-Merge Checklist
- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog
:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by DeltaDav** [comment]
My french brain took over, let me correct all mention of it

**Comment by K4rlox** [comment]
most vehicles including the one in enclave dont have a power cell


supermutants get attacked by their friends own faction mobs
ncr npcs maul NCR players

**Comment by GuyGuysonF19** [comment]
This will split the pop awfully, cool map but poor implementation, lacking the infrastructure to actually make this work, should probably be disabled until there is code and pop for this

**Comment by DeltaDav** [comment]
Closing PR, since... Well, Mexico is returning smaller.

**Pull request closed without merging**
