### PR TITLE
Custom Loadout Overhaul

### PR DESCRIPTION
**Pull request by SirSwagmeyer**
## About The Pull Request
Adds a massive amount of new and overlooked cosmetic/minor items to the custom loadout menu. Any especially powerful armor pieces are cosmetic kit replacements to the original role, so they'll be role restricted. 

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Added a MASSIVE amount of loadout items to the character creation screen. I literally can't list all of them here. 
/:cl:

### CODE REVIEW

**Comment by oprimeolt** [comment]
swag stop making prs like this...vetranger gear for ncr cap? WORKING stealthsuits for anyone? I didnt even read past those and it already seems BS

**Comment by SirSwagmeyer** [comment]
> swag stop making prs like this...vetranger gear for ncr cap? WORKING stealthsuits for anyone? I didnt even read past those and it already seems BS
Did you even read my fucking PR? The stealth suits dont work, its purely cosmetic, and the NCR Captain part was mostly a code oversight, I needed at least two I jobs for the whitelist to work for some reason, so I picked the highest ranked job alongside Vet Ranger. I'm gonna fix it later.

**Comment by Aurrain** [comment]
Oli suggested using modkits for the faction armors, and I think that is a great idea especially for the more problematic & duplicate-able ones.

**Comment by Aurrain** [comment]
File conflicts, also asking once more your opinion on using modkits for faction armors.

**Comment by SirSwagmeyer** [comment]
> File conflicts, also asking once more your opinion on using modkits for faction armors.

If you could tell me which items are going to get converted into modkits, I'll take them out of the code to get this merged. Honestly, I don't think it'll make much of a difference from just adding the armor themselves and having it locked behind roles instead of dedicated modkits, but that's up to you guys.

**Pull request merged**
